server:
  port: 8080
  servlet:
    context-path: /api/
  error:
    include-message: always
spring:
  application:
    name: cinema
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:3306/cinemadb
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    configuration:
      url: jdbc:mysql://${DB_HOSTNAME:localhost}:3306/cinemadb
      user: root
      password: admin
      baselineOnMigrate: true
      schemas:
        - public
  logging:
    level:
      root: WARN
      com.nagarro.af24.cinema: INFO
    file:
      name: logs/appLog.log
    pattern:
      file: "%d [%level] %c{1.} [%t] %m%n"
  mail:
    host: smtp.gmail.com
    port: 587
    username: r.vlad0856@gmail.com
    password: ranq cxom emxh hvow
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

variables:
  image:
    path:
      movies: D:/nagarro/images/movies
      actors: D:/nagarro/images/actors