server:
  port: 8080
  servlet:
    context-path: /api/
  error:
    include-message: always
spring:
  application:
    name: cinema
  datasource:
    url: jdbc:mysql://localhost:3306/cinemadb
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    validate-on-migrate: true
    locations: classpath:db/migration
    configuration:
      url: jdbc:mysql://localhost:3306/cinemadb
      user: root
      password: admin
      baselineOnMigrate: true
      schemas:
        - public
  logging:
    level:
      root: WARN
      com.nagarro.af24.cinema: INFO
    file:
      name: logs/appLog.log
    pattern:
      file: "%d [%level] %c{1.} [%t] %m%n"