server:
  port: 8080
  servlet:
    context-path: /api/
  error:
    include-message: always
spring:
  application:
    name: cinema
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinemadb
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    configuration:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cinemadb
      user: root
      password: admin
      baselineOnMigrate: true
      schemas:
        - public