version: "3.8"

services:
  cinema-db:
    image: mysql
    container_name: db-cinema
    restart: on-failure
    ports:
      - "3006:3306"
    environment:
      MYSQL_DATABASE: cinemadb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - cinema-network

  cinema-app:
    hostname: cinema-management
    restart: on-failure
    depends_on:
      - cinema-db
    image: cinema-management-app
    container_name: cinema-management-container
    build: .
    ports:
      - "8000:8080"
    environment:
      - DB_HOSTNAME=cinema-db
    networks:
      - cinema-network

networks:
  cinema-network:
    external: true