delete from movie_actor;
delete from movie_genre;
delete from reviews;
delete from movie_images_paths;
delete from movies;
delete from actors;
delete from user_role_junction;
delete from otp;
delete from users;